// GENERE par agents/_chassis/export_catalogue.py depuis agents/<slug>/README.md. Ne pas editer a la main.
// Relancer le script apres toute modification d'un README d'agent.
export type AgentStats = { autonomie: number; souverainete: number; integration: number; impact: number; installation: number };
export type B2BAgent = { slug: string; name: string; tag: string; date: string; img: string; pitch: string;
  description: string[]; features: string[]; stack: string[]; price: string; cta: string; future: boolean;
  edition: string; type: string; element: string; stats: AgentStats; prix: number | null; prix_souverain: number | null };
export const B2B_AGENTS: B2BAgent[] = [
  {
    slug: "devis-relance",
    name: "Devis-Relance",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/devis-relance.webp",
    pitch: "l'agent qui ne laisse plus mourir un devis",
    description: ["Un devis envoyé sans relance a une chance sur cinq d'être signé. Relancer demande du temps, du tact et de la régularité : trois choses qu'un dirigeant n'a pas le mardi à 18 h.", "Chaque devis est relancé trois fois, au bon moment (J+3, J+10, J+20), avec un message court qui suit le contexte, et jamais sans votre validation. Les réponses des clients sont classées et la suite est préparée. Vous validez, l'agent rédige.", "Il n'envoie rien. Il ne touche ni prix, ni remise, ni délai. Il ne relance jamais plus de trois fois."],
    features: ["Vous enregistrez un devis (client, montant, date, deux lignes de contexte).", "À chaque échéance, il rédige la relance et la dépose dans votre file « à valider ».", "Vous collez la réponse du client : il la classe (intéressé, objection, refus, plus tard, hors", "Chaque jour, il mesure son taux de réponse et son taux de signature à 30 jours."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "490 € cloud · 990 € souverain · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "PME · artisans · agences",
    element: "cash",
    stats: {"autonomie": 3, "souverainete": 4, "integration": 3, "impact": 5, "installation": 1},
    prix: 490,
    prix_souverain: 990,
  },
  {
    slug: "factur-agent",
    name: "Factur-Agent : l'agent qui rapproche vos factures et ne laisse passer aucune anomalie",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/factur-agent.webp",
    pitch: "Depuis le 1er septembre 2026, toute entreprise doit pouvoir recevoir des factures électroniques (Factur-X, UBL) ; les PME et TPE devront en ",
    description: ["Depuis le 1er septembre 2026, toute entreprise doit pouvoir recevoir des factures électroniques (Factur-X, UBL) ; les PME et TPE devront en émettre au 1er septembre 2027. Les factures arrivent dans trois formats, personne ne les rapproche des devis, une TVA fausse ou un doublon passe, et les impayés se découvrent à la clôture.", "Chaque facture est lue, rapprochée d'un devis ou d'une commande, contrôlée (TVA, total, doublon, montant hors devis) et transformée en écriture prête à importer. Ce qui est propre passe seul ; ce qui est douteux vous est présenté. Les impayés sont listés et la relance est rédigée, jamais envoyée sans vous.", "Il n'envoie rien, ne paie rien, n'écrit pas dans votre comptabilité. Il n'invente jamais un montant ou un numéro manquant. Il ne relance ni une facture reçue, ni une facture payée."],
    features: ["Vous enregistrez vos devis et commandes (tiers, montant HT, taux de TVA, achat ou vente).", "Vous lui donnez une facture : champs structurés (Factur-X, UBL simplifié) ou texte d'un PDF.", "Il extrait, rapproche, contrôle. Statut `rapprochee` ou `a_verifier` avec les anomalies typées.", "Il liste les impayés (échéance dépassée) et, sur une facture émise, rédige la relance dans", "Il produit l'export d'écritures JSON (journal ACH ou VEN, lignes équilibrées) que vous importez"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "1270 € cloud · 1770 € souverain · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "PME · cabinets comptables",
    element: "conformite",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 5, "impact": 5, "installation": 3},
    prix: 1270,
    prix_souverain: 1770,
  },
  {
    slug: "guichet-mail",
    name: "Guichet-Mail : l'agent qui trie votre boîte contact@ et prépare chaque réponse",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/guichet-mail.webp",
    pitch: "La boîte contact@ reçoit tout : une fuite d'eau, une facture, un CV, une demande de salle et trois spams, dans le même flux. Personne n'a le",
    description: ["La boîte contact@ reçoit tout : une fuite d'eau, une facture, un CV, une demande de salle et trois spams, dans le même flux. Personne n'a le temps de trier, l'urgence attend derrière la publicité, et la réponse part trois jours plus tard.", "Chaque mail est classé, orienté vers la bonne personne et rangé dans une file triée par priorité. Le brouillon de réponse est rédigé à partir de vos documents, jamais inventé, et attend votre validation. Vous voyez chaque jour combien de mails attendent, depuis combien de temps, et votre délai médian de réponse.", "Il n'envoie rien. Il ne supprime rien, même un spam. Il n'invente ni horaire, ni tarif, ni engagement absent de votre base documentaire."],
    features: ["Votre outil lui pousse chaque mail reçu (expéditeur, objet, corps).", "Il le classe (urgent, demande, facture, candidature, spam, autre) et propose le destinataire", "La file d'attente est triée : urgences d'abord, puis les plus anciens.", "Sur demande, il rédige un brouillon à partir de `data/base.md` (vos horaires, tarifs,", "Vous confirmez ou corrigez la classe : c'est sa note. Vous indiquez quand la réponse est"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "490 € cloud · 990 € souverain · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "PME · mairies · assos",
    element: "temps",
    stats: {"autonomie": 4, "souverainete": 4, "integration": 3, "impact": 4, "installation": 1},
    prix: 490,
    prix_souverain: 990,
  },
  {
    slug: "mairiebot",
    name: "MairieBot : l'accueil citoyen qui ne répond que ce qu'il sait",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/mairiebot.webp",
    pitch: "L'accueil d'une mairie répète les mêmes réponses toute la journée : horaires, pièces à fournir, jour de ramassage, inscription à la cantine.",
    description: ["L'accueil d'une mairie répète les mêmes réponses toute la journée : horaires, pièces à fournir, jour de ramassage, inscription à la cantine. Pendant ce temps, les demandes qui exigent un humain attendent. Et un accueil automatique classique invente des horaires : inacceptable en mairie.", "Un accueil multi-canal (site, WhatsApp, SMS, mail) qui répond uniquement à partir des documents de la commune, cite le document et sa date, et passe la main au bon service dès qu'il ne sait pas. Chaque question sans réponse est notée pour enrichir la base à la prochaine mise à jour.", "Il n'invente jamais un horaire, un tarif, un délai. Il ne prend aucune décision administrative. Il ne demande ni numéro de sécurité sociale, ni pièce d'identité, ni IBAN ; si une question en contient, elle n'est ni stockée ni transmise au moteur. Il ne publie rien et ne modifie pas la base documentaire : ce sont des checkpoints humains."],
    features: ["La mairie dépose ses documents (horaires, tarifs, règlements) en Markdown dans `data/commune/`.", "Un habitant pose une question : l'agent cherche dans la base, répond en trois temps (réponse,", "Hors base : il donne le service compétent et note le sujet manquant dans `data/manques.jsonl`.", "L'accueil peut noter chaque réponse juste ou fausse : c'est la mesure de qualité.", "Statistiques des sujets fréquents pour savoir quoi documenter en priorité."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "1470 € souverain (installé chez vous) · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "Mairies · intercos",
    element: "citoyen",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 3, "impact": 4, "installation": 3},
    prix: null,
    prix_souverain: 1470,
  },
  {
    slug: "delib-scribe",
    name: "Délib-Scribe : le procès-verbal prêt à relire le lendemain de la séance",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/delib-scribe.webp",
    pitch: "Un conseil municipal de trois heures, c'est deux jours de secrétariat pour un procès-verbal, avec des obligations de publication et d'access",
    description: ["Un conseil municipal de trois heures, c'est deux jours de secrétariat pour un procès-verbal, avec des obligations de publication et d'accessibilité. Les votes se perdent dans les échanges, les points s'entremêlent, et le document final arrive tard.", "Vous déposez l'ordre du jour et la transcription de la séance ; l'agent rend un procès-verbal structuré, point par point (exposé, débats, décision, vote), en Markdown accessible, et vous dit exactement quels passages relire. Vous validez, il propose une date de publication. Il ne publie jamais lui-même.", "Il ne transcrit pas l'audio : la transcription est faite en amont, en local, par VoiceBox (Whisper), hors de cet agent. Il n'invente ni vote, ni décision, ni intervenant. Il ne publie rien, n'envoie rien, ne transmet rien au contrôle de légalité."],
    features: ["Vous envoyez la séance : date, organe, ordre du jour, transcription texte.", "Il découpe la transcription par point de l'ordre du jour ; un point introuvable est signalé.", "Pour chaque point : exposé, débats résumés, décision, vote (pour, contre, abstention). Le vote", "Il rend le procès-verbal Markdown et la liste des points à relire.", "Vous validez en déclarant les points corrigés et le temps gagné : il propose une date de"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "1470 € souverain (installé chez vous) · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "Mairies · syndicats",
    element: "temps",
    stats: {"autonomie": 3, "souverainete": 5, "integration": 2, "impact": 4, "installation": 3},
    prix: null,
    prix_souverain: 1470,
  },
  {
    slug: "marches-subventions",
    name: "Marchés-Subventions : l'agent qui ne rate plus une opportunité",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/marches-subventions.webp",
    pitch: "Les appels d'offres et les subventions se ratent faute de veille, ou se découvrent dix jours avant l'échéance quand le dossier demande trois",
    description: ["Les appels d'offres et les subventions se ratent faute de veille, ou se découvrent dix jours avant l'échéance quand le dossier demande trois semaines. Personne n'a le temps de lire toutes les plateformes, encore moins de monter un dossier par opportunité.", "Vous décrivez votre structure une fois (type, région, secteurs, budget, mots-clés). Chaque opportunité reçue est scorée de 0 à 100 par des règles lisibles, documentée en une fiche (échéance, pièces, points forts et faibles), et le dossier est pré-rempli à partir de vos documents. Les rappels d'échéance vous sont proposés ; vous validez, l'agent ne dépose rien.", "Il ne dépose rien, n'envoie rien. Il n'invente ni montant, ni pièce, ni échéance, ni donnée de votre structure. **Dans cette version, il ne collecte pas encore lui-même** : la collecte automatique BOAMP, aides-territoires et plateformes régionales est un connecteur à venir ; les opportunités sont soumises via l'API ou importées d'un fichier JSON."],
    features: ["Vous déclarez votre profil (`PUT /profil`).", "Vous soumettez une opportunité, ou vous en importez une liste depuis `data/opportunites.json`.", "Il score chaque opportunité et explique le score (région, secteurs, mots-clés, budget, délai).", "Il produit la fiche, puis pré-remplit le dossier depuis `data/structure.md` en marquant", "Il propose un rappel pour chaque échéance proche (checkpoint humain)."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "990 € cloud · 1470 € souverain · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "Mairies · assos · PME",
    element: "cash",
    stats: {"autonomie": 4, "souverainete": 3, "integration": 3, "impact": 5, "installation": 2},
    prix: 990,
    prix_souverain: 1470,
  },
  {
    slug: "traffic-sentinel",
    name: "Traffic-Sentinel : l'agent qui lit vos journaux à votre place",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/traffic-sentinel.webp",
    pitch: "Une part croissante du trafic d'un site n'est pas humaine : crawlers IA qui aspirent les pages, scanners qui testent `/.env` et `/wp-login.p",
    description: ["Une part croissante du trafic d'un site n'est pas humaine : crawlers IA qui aspirent les pages, scanners qui testent `/.env` et `/wp-login.php`, scripts en rafale. Les serveurs encaissent, la facture d'hébergement monte, et personne n'a le temps de lire les journaux.", "Chaque source de trafic est classée par des règles lisibles (humain, robot utile, crawler IA, suspect), avec la raison exacte. Vous recevez un rapport en français courant et des règles de blocage ou de limitation prêtes à coller dans Traefik ou nginx. Vous validez, l'agent ne touche jamais à votre proxy.", "Il n'applique aucune règle. Il ne modifie ni Traefik, ni nginx, ni un pare-feu. Il n'envoie aucune adresse IP hors de votre machine. Il ne consulte aucune base de réputation externe."],
    features: ["Vous lui envoyez vos lignes de journal par lots (`POST /logs`, JSON Traefik/nginx ou format", "Il agrège par adresse IP et user-agent sur une fenêtre glissante (60 minutes par défaut) et", "Vous confirmez ou corrigez ses classes : chaque correction est un faux positif mesuré.", "Pour une source, il propose une règle (`bloquer` ou `rate_limit`) : labels Traefik, snippet", "Chaque jour, il résume la fenêtre pour un dirigeant : part du trafic non humain, crawlers les"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "1770 € souverain (installé chez vous) · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "Grandes structures · médias",
    element: "securite",
    stats: {"autonomie": 5, "souverainete": 5, "integration": 4, "impact": 4, "installation": 5},
    prix: null,
    prix_souverain: 1770,
  },
  {
    slug: "edge-optimizer",
    name: "Edge-Optimizer : l'agent qui rend votre site rapide et lisible par les IA",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/edge-optimizer.webp",
    pitch: "« On n'est pas visible. » Derrière cette phrase : un site qui met trois secondes à répondre, des photos de 4 Mo, pas de balise description, ",
    description: ["« On n'est pas visible. » Derrière cette phrase : un site qui met trois secondes à répondre, des photos de 4 Mo, pas de balise description, et une absence totale dans les moteurs de réponse IA qui commencent à remplacer la recherche classique.", "Un score clair sur 100, en quatre catégories (performance, images, SEO technique, moteurs de réponse), et la liste des correctifs classés par ce qu'ils rapportent pour ce qu'ils coûtent, chacun avec le bout de code ou la commande à coller. Vous appliquez, l'agent mesure le progrès d'un audit à l'autre.", "Il ne touche pas au site. Il ne fait aucune requête réseau dans cette version : le collecteur de pages est un connecteur à venir, en attendant vous lui donnez le JSON d'un audit Lighthouse ou un relevé manuel. Il ne promet ni classement ni trafic."],
    features: ["Vous lui donnez le rapport d'une page en JSON (poids, images, balises, protocole, temps de", "Il calcule les quatre scores par des règles fixes, puis la liste des correctifs : compression", "Il rédige deux phrases de résumé pour un dirigeant.", "Il génère votre `llms.txt` et votre bloc schema.org Organization depuis vos informations", "Vous lui dites ce que vous avez accepté, refusé ou appliqué (`POST /applique/{id}`) ; au"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "690 € cloud · 1190 € souverain · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "Assos · PME · vitrines",
    element: "visibilite",
    stats: {"autonomie": 2, "souverainete": 4, "integration": 3, "impact": 4, "installation": 2},
    prix: 690,
    prix_souverain: 1190,
  },
  {
    slug: "conformite-agent",
    name: "Conformité-Agent : l'agent qui tient vos registres RGPD et IA et ne rate aucune échéance",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/conformite-agent.webp",
    pitch: "L'AI Act s'applique pour l'essentiel depuis le 2 août 2026, le RGPD impose un registre des traitements depuis 2018, NIS2 arrive pour les col",
    description: ["L'AI Act s'applique pour l'essentiel depuis le 2 août 2026, le RGPD impose un registre des traitements depuis 2018, NIS2 arrive pour les collectivités : trois registres à tenir, des revues annuelles, des analyses d'impact, des demandes d'accès à traiter sous un mois. Personne ne les tient, et on le découvre le jour du contrôle ou de la demande.", "Deux registres toujours à jour (traitements RGPD, systèmes d'IA), chaque entrée notée complète ou non avec la liste de ce qui manque, un calendrier d'échéances qui alerte avant la date, une fiche d'information et une réponse type prêtes à valider. L'agent cite le texte et propose ; votre responsable, votre DPO ou votre conseil décide. Jamais d'avis juridique automatique.", "Il ne publie rien, n'envoie rien, ne modifie aucune entrée seul. Il ne dit jamais « conforme » ni « en infraction ». Il ne choisit ni base légale, ni niveau de risque, ni durée à votre place."],
    features: ["Vous enregistrez chaque traitement (finalité, base légale, données, durée, risque, mesures)", "Il mesure la complétude et liste les champs manquants, article de référence à l'appui.", "Il calcule les échéances : revue annuelle, DPIA si risque élevé, documentation technique si", "Sur demande, il rédige la fiche d'information d'un traitement et la dépose « à valider ».", "Vous collez une demande d'accès : il prépare l'accusé de réception et la réponse type, sans"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "1770 € souverain (installé chez vous) · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "ETI · collectivités",
    element: "conformite",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 3, "impact": 4, "installation": 4},
    prix: null,
    prix_souverain: 1770,
  },
  {
    slug: "asso-mobilise",
    name: "Asso-Mobilise : l'agent qui tient votre association ensemble",
    tag: "Agent · B2B · déployable",
    date: "09 / 2026",
    img: "/monthly/asso-mobilise.webp",
    pitch: "Des bénévoles qu'on ne sait plus qui appeler, des cotisations qui traînent parce que personne n'ose relancer, des événements annoncés la vei",
    description: ["Des bénévoles qu'on ne sait plus qui appeler, des cotisations qui traînent parce que personne n'ose relancer, des événements annoncés la veille sur un seul réseau, une newsletter « qu'on devrait faire ». Tout repose sur deux personnes du bureau, le soir.", "Une base à jour des membres et de leurs compétences, les relances rédigées au bon ton et prêtes à envoyer, les bénévoles proposés poste par poste pour chaque événement, quatre semaines de posts planifiés sur vos canaux et la newsletter du mois en brouillon. Vous validez, l'agent rédige.", "Il n'envoie rien et ne publie rien. Il ne radie personne, n'encaisse rien, ne relance jamais plus de trois fois. Il ne se connecte à aucun réseau social dans cette version : il produit les textes, vous les collez."],
    features: ["Vous enregistrez vos membres (rôle, compétences, cotisation) et vos événements (date, lieu,", "Il liste les cotisations en retard et rédige, sur demande, une relance chaleureuse (trois au", "Pour chaque événement, il propose qui mettre sur quel poste selon les compétences et vous dit", "Il génère un calendrier éditorial de quatre semaines : un post par canal et par semaine (site,", "Il enregistre les inscriptions en ligne à vos événements et compte les places."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "390 € cloud · 890 € souverain · mise à jour 120 € / 4 mois · sans abonnement",
    cta: "Demander une démo",
    future: false,
    edition: "Septembre 2026",
    type: "Associations · clubs",
    element: "reseau",
    stats: {"autonomie": 3, "souverainete": 3, "integration": 4, "impact": 4, "installation": 2},
    prix: 390,
    prix_souverain: 890,
  },
  {
    slug: "acheteur-agentique",
    name: "Acheteur agentique",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/acheteur-agentique.webp",
    pitch: "PME avec achats récurrents (consommables, pièces, énergie, fournitures), associations gestionnaires (EHPAD, centres de loisirs), services achats de mairies sous",
    description: ["le dirigeant ou la secrétaire passe des heures à comparer, commander, relancer. Les prix bougent, les fournisseurs changent, personne ne renégocie.", "il porte un mandat borné (plafond, catégories, fournisseurs autorisés, délais), interroge les catalogues et les agents fournisseurs, négocie, commande et paie via un rail agentique, puis rapproche la facture. Il rend compte chaque semaine : « 3 commandes, 412 EUR économisés, 1 fournisseur à valider ».", "sécurité x402 (analyse « Free-Riding the Agentic Web », arXiv 2605.30998) ; responsabilité contractuelle d'un achat passé par agent ; Gartner prévoit l'abandon de 40 % des projets agentiques d'ici fin 2027 faute de valeur mesurée."],
    features: [" Rails de paiement agentiques en production : ACP (OpenAI + Stripe, Apache 2.0, « Buy it in ChatGPT » lancé le 16/02/2026 avec 1 M de marchands Shopify à venir) (openai.com, stripe.com) ; AP2 soutenu par 60+ acteurs (Linux Foundation) ; x402 Foundation (Visa, Mastercard, Amex, Stripe) (coindesk).", " Identité et délégation d'agent : OpenID AuthZEN publie les profils AARP et COAZ (autorisation d'outils MCP) (openid.net) ; NIST liste 6 standards d'identité d'agent.", " Ce qui manque : des fournisseurs français qui exposent un point d'entrée agentique et une chaîne de délégation OAuth multi-sauts normalisée. Projection : bascule B2B en 2027, après la B2C 2026."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "PME · achats",
    element: "cash",
    stats: {"autonomie": 5, "souverainete": 3, "integration": 5, "impact": 4, "installation": 3},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "ambassadeur-inter-agents",
    name: "Ambassadeur inter-agents",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/ambassadeur-inter-agents.webp",
    pitch: "PME B2B vendeuses (grossistes, sous-traitants industriels, imprimeurs, prestataires), coopératives, offices de tourisme.",
    description: ["demain, l'acheteur ne lit plus votre site : son agent interroge une carte d'agent. Sans point d'entrée agentique, la PME devient invisible, comme sans site web en 2010 (43 % des associations n'ont déjà pas de présence numérique) (une-association.org).", "il publie une Agent Card A2A signée, expose le catalogue, les délais, les conditions ; il répond aux agents acheteurs (demandes de devis, disponibilité, personnalisation), qualifie, propose un prix dans les marges autorisées, et passe la main à l'humain au-delà. Il est le pendant vendeur de l'Acheteur agentique (fiche 3). Distinct de « relance devis » (2026) : ici l'interlocuteur est un agent, pas un humain.", "injection de prompt par des agents adverses ; révélation de marges ; faux agents acheteurs (d'où signature des cartes)."],
    features: [" A2A v1.0 avec Agent Cards signées, intégré à Azure AI Foundry, Copilot Studio, Bedrock AgentCore ; 150+ organisations ; production en supply chain, finance, assurance (linuxfoundation.org, 9/04/2026).", " A2A hébergé par l'AAIF aux côtés de MCP depuis le 17/08/2026 (Forbes, pebblous).", " Registre d'agents consolidé (« consolidation of efforts for registry » dans la feuille de route A2A) et découverte inter-entreprises fiable : projection 2027."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "Toute structure vendeuse",
    element: "reseau",
    stats: {"autonomie": 5, "souverainete": 4, "integration": 4, "impact": 4, "installation": 3},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "civitai-exhauster",
    name: "Civitai-Exhauster",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/civitai-exhauster.webp",
    pitch: "agent 2027, spécifié par Naim le 15/09/2026",
    description: ["« Il épluche Civitai en live et comprend, au prompt de l'utilisateur, quel modèle lui conviendrait le mieux. Il en fait une image ISO, l'utilise, et le crame. »", "1. **Épluchage en direct** : interroger l'API Civitai (recherche par tags, type checkpoint / LoRA, base model, licence, note, téléchargements) à chaque prompt utilisateur, pas un index figé. 2. **Compréhension du prompt** : un modèle local lit le prompt de l'utilisateur, en déduit style, sujet, contraintes (photoréaliste, anime, pixel art, NSFW interdit, licence commerciale requise), et classe les candidats Civitai. 3. **Image ISO** : empaqueter le modèle choisi et ses dépendances dans un environnement éphémère (conteneur ou volume jetable), le charger dans ComfyUI / le pool GPU, générer. 4. **Le cramer** : détruire l'environnement après usage. Rien ne reste sur disque, aucun poids ne s'accumule, pas de collection à maintenir.", "Garder un modèle sans licence compatible · générer sans passer par la modération · conserver un poids après la session."],
    features: ["**Épluchage en direct** : interroger l'API Civitai (recherche par tags, type checkpoint / LoRA,", "**Compréhension du prompt** : un modèle local lit le prompt de l'utilisateur, en déduit style,", "**Image ISO** : empaqueter le modèle choisi et ses dépendances dans un environnement éphémère", "**Le cramer** : détruire l'environnement après usage. Rien ne reste sur disque, aucun poids ne"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "MegaStudio · add-on",
    element: "studio",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 3, "impact": 3, "installation": 3},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "compagnon-de-chantier",
    name: "Compagnon de chantier",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/compagnon-de-chantier.webp",
    pitch: "artisans du bâtiment, PME de maintenance industrielle, techniciens terrain (chauffage, électricité, ascenseurs), régies techniques de mairies.",
    description: ["65 % des recrutements du BTP sont jugés difficiles (BMO 2026), 5 mois en moyenne pour recruter un maçon ou un couvreur qualifié (baromètre CAPEB 2026). Le savoir des anciens part avec eux ; le jeune sur le chantier appelle le patron dix fois par jour.", "l'ouvrier porte des lunettes connectées ou pose son smartphone ; l'agent voit ce qu'il voit, écoute, et guide en voix naturelle (« la gaine que tu tiens n'est pas la bonne section, prends la 20 »). Il lit les notices, les plans DWG/PDF de l'entreprise, les normes (DTU), consigne automatiquement les photos avant/après, remplit le rapport d'intervention et l'auto-contrôle. Mode « expert distant » : le patron peut prendre la main en visio si l'agent doute.", "sécurité physique (une consigne fausse blesse quelqu'un : toujours « conseil », jamais « ordre ») ; RGPD image des tiers sur chantier ; batterie et poussière ; responsabilité décennale non transférée à l'agent."],
    features: [" Modèles vision natifs locaux : Qwen3.8-27B (vision native, 262K contexte, Apache 2.0) tient sur un seul GPU 24 Go (codersera, HF).", " Voix full-duplex ouverte : Kyutai Unmute (transcription + synthèse temps réel, détection de fin de parole sémantique) et Moshi, labo parisien à but non lucratif (frenchweb, kyutai.org).", " Lunettes AR déjà en production industrielle 2026, marché 8 Mds USD +16,5 %/an, gain jusqu'à 30 % de temps sur les tâches complexes (oxmaint, treeview).", " Ce qui manque en 2026 : la boucle vidéo + voix + raisonnement en moins d'une seconde, en local sur un boîtier de chantier (pas de réseau fiable en sous-sol). Projection : 2027, portée par les NPU 80 TOPS (Snapdragon X2 Elite) et l'arrivée des runtimes NPU (Windows AI Foundry / Foundry Local, WSL3 passthrough annoncés à Build 2026, encore « early ») (whysogeek, digitalapplied)."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "BTP · maintenance",
    element: "terrain",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 3, "impact": 5, "installation": 4},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "contremaitre-de-flotte-robots",
    name: "Contremaître de flotte robots",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/contremaitre-de-flotte-robots.webp",
    pitch: "PME logistique et e-commerce (entrepôt < 3 000 m2), ateliers de sous-traitance, exploitations agricoles et maraîchères, services techniques de mairies (nettoyag",
    description: ["main d'œuvre introuvable sur les postes pénibles ; les robots deviennent abordables mais chaque marque a son logiciel, personne en interne ne sait les programmer.", "un agent unique donne des consignes en langage naturel à une petite flotte hétérogène (AMR, bras collaboratif, robot de nettoyage), planifie les tâches de la journée, surveille par caméra, arrête tout en cas d'anomalie, et tient le journal de sécurité. L'humain garde le bouton rouge et valide les nouvelles tâches.", "règlement machines 2023/1230 (application 20/01/2027) et sécurité des personnes ; assurance ; acceptation sociale ; dépendance à un constructeur asiatique pour le matériel."],
    features: [" Modèles ouverts vision-langage-action : Mistral Robostral Navigate 8B (navigation avec une seule caméra RGB, hardware-agnostique, juillet 2026), acquisition Emmi AI, clients Airbus et BMW (Bloomberg, siliconrepublic) ; SmolVLA open source.", " Matériel abordable : Unitree R1 à 5 900 USD sur AliExpress ; Optimus annoncé à 20 000 USD avec déploiement usine visé 2027 ; un robot NVIDIA tient un poste de 8 h chez Siemens (laterredufutur, lefilia).", " Les sources françaises jugent l'impact « marginal » en 2026-2027 et voient l'accélération 2027-2028 en logistique, palettisation, inspection légère (lefilia). Le prérequis réel est un VLA ouvert capable de manipulation fiable, pas seulement de navigation : projection fin 2027.", " AI Act : les systèmes intégrés à des machines (Annexe I) sont repoussés au 2/08/2028 (donneespersonnelles.fr), ce qui laisse une fenêtre 2027 pour les pilotes."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "Logistique · agriculture",
    element: "terrain",
    stats: {"autonomie": 5, "souverainete": 4, "integration": 4, "impact": 5, "installation": 5},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "gardien-produit-connecte",
    name: "Gardien produit connecté",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/gardien-produit-connecte.webp",
    pitch: "PME éditrices de logiciels, fabricants d'objets connectés, intégrateurs domotique/industriel, startups hardware.",
    description: ["le Cyber Resilience Act impose depuis le 11/09/2026 le signalement des vulnérabilités activement exploitées et des incidents (art. 14), et s'applique en totalité le 11/12/2027 (sécurité par conception, évaluation de conformité, SBOM, gestion des vulnérabilités) (Freshfields, Privacy World, digital-strategy.ec.europa.eu). Une PME de 8 personnes n'a pas de RSSI.", "il maintient la nomenclature logicielle (SBOM) de chaque produit, surveille les CVE des composants, qualifie l'exploitation active, prépare et dépose les notifications (24 h alerte, 72 h notification, rapport final) sur la plateforme unique ENISA, tient le dossier technique CRA et propose les correctifs. Distinct du « registre AI Act/RGPD/NIS2 » 2026 : ici on gère le produit vendu, pas l'organisation.", "faux positifs de CVE ; secret industriel dans les SBOM ; sanction CRA jusqu'à 15 M EUR ou 2,5 % du CA (régime CRA) ; l'agent ne signe pas la déclaration de conformité."],
    features: [" CRA : reporting 11/09/2026, application complète 11/12/2027.", " Modèles de code agentiques ouverts capables d'auditer un dépôt entier : Devstral 2 (Mistral), Qwen3.6-27B « meilleur modèle local pour le code agentique » (codersera, mistral.ai).", " Plateforme unique de notification ENISA pleinement opérationnelle et normes harmonisées CRA publiées : projection 2027."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "Fabricants d'objets connectés",
    element: "securite",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 4, "impact": 4, "installation": 4},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "guichet-eudi",
    name: "Guichet EUDI",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/guichet-eudi.webp",
    pitch: "mairies (état civil, inscriptions scolaires, urbanisme), associations (adhésions, licences), PME soumises à la LCB-FT (immobilier, comptables, assurance), organ",
    description: ["justificatifs papier, photocopies de CNI stockées sans base légale, files d'attente. Le portefeuille européen d'identité numérique arrive fin 2026 et son acceptation devient obligatoire pour une longue liste d'acteurs le 24/12/2027 (donneespersonnelles.fr, docaposte, whaller).", "il accepte les attestations vérifiables du wallet (identité, domicile, diplôme, permis), vérifie la signature, ne conserve que le strict nécessaire, pré-remplit le dossier (inscription, adhésion, demande d'urbanisme) et délivre en retour une attestation signée par la collectivité ou l'association. Distinct de « accueil citoyen mairie » 2026 (chat d'information) : ici on traite la preuve, pas la question.", "fracture numérique (toujours un guichet humain) ; RGPD minimisation ; dépendance aux spécifications nationales encore mouvantes."],
    features: [" Règlement (UE) 2024/1183 (eIDAS 2), wallets nationaux d'ici fin 2026, acceptation obligatoire 24/12/2027 ; usage volontaire pour le citoyen, alternative physique maintenue.", " Publication des spécifications françaises de connexion (France Identité comme wallet) et d'un SDK vérifieur utilisable par une mairie de 2 000 habitants."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3", "Mistral API (option)"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "Mairies · assos",
    element: "citoyen",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 4, "impact": 4, "installation": 3},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "interprete-de-guichet",
    name: "Interprète de guichet",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/interprete-de-guichet.webp",
    pitch: "mairies et CCAS, associations d'accueil et d'insertion, maisons France Services, PME employant des salariés allophones, offices de tourisme.",
    description: ["un usager ne parle pas français, l'agent d'accueil non plus sa langue ; l'interprète coûte et n'est pas là. Les outils cloud posent un problème de confidentialité (dossiers sociaux, santé).", "traduction vocale simultanée dans les deux sens, en local, sur une tablette ou un petit boîtier au guichet, avec affichage du texte et résumé écrit remis à l'usager. Vocabulaire administratif français (CAF, urbanisme, état civil) chargé en mémoire. Synergie directe avec Palabra Dabra (14 langues) pour les glossaires.", "erreur de traduction sur un acte juridique (toujours un texte écrit à relire) ; qualité inégale selon la langue ; accessibilité (EAA) à respecter."],
    features: [" Kyutai (Paris, non lucratif, 300 M USD) publie Moshi (full-duplex), Hibiki (traduction simultanée) et Unmute en open source (frenchweb, studeria, recatools).", " Latence < 1 s « table stakes » chez tous les fournisseurs 2026 (assemblyai, inworld).", " Ce qui manque : le tout en local sur une tablette NPU (40-80 TOPS) avec 14 langues et un accent régional variable. Les NPU 2026 ne servent pas encore les LLM (Ollama retombe sur CPU) (whysogeek) ; projection 2027 avec Windows AI Foundry / runtimes NPU."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "Mairies · santé · accueil",
    element: "citoyen",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 2, "impact": 4, "installation": 2},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "lip-sync-performer",
    name: "Lip-Sync-Performer",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/lip-sync-performer.webp",
    pitch: "agent 2027, spécifié par Naim le 15/09/2026",
    description: ["« Il améliore le réalisme d'une scène de dialogue en modifiant son plan et sa vue, avec des données sur l'histoire des meilleurs plans cinématographiques, et l'ajout d'un DLSS 10. »", "1. **Synchronisation labiale** : à partir d'une scène de dialogue (vidéo + piste voix VoiceBox), régénérer le visage pour que les lèvres suivent la voix (MuseTalk déjà installé dans `softwares/musetalk/`, LTX-2.5 audio synchronisé natif, Wan). 2. **Recadrage cinématographique** : une base de connaissances des plans (champ-contrechamp, règle des 180°, gros plan sur la réplique clé, amorce d'épaule) tirée de l'histoire du cinéma ; l'agent choisit le plan et la vue qui servent la scène, et régénère ou recadre. 3. **Upscaling temps réel nouvelle génération** (« DLSS 10 ») : reconstruction haute définition et lissage temporel à la volée, sans rendu long.", "Reproduire le visage d'un acteur réel ou une marque à l'identique (limite parodie, doctrine Conspix) · sortir un plan sans passer par la modération."],
    features: ["**Synchronisation labiale** : à partir d'une scène de dialogue (vidéo + piste voix VoiceBox),", "**Recadrage cinématographique** : une base de connaissances des plans (champ-contrechamp,", "**Upscaling temps réel nouvelle génération** (« DLSS 10 ») : reconstruction haute définition"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "MegaStudio · add-on",
    element: "studio",
    stats: {"autonomie": 3, "souverainete": 5, "integration": 3, "impact": 4, "installation": 4},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "megaupgame",
    name: "Megaupgame",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/megaupgame.webp",
    pitch: "agent 2027, spécifié par Naim le 15/09/2026",
    description: ["« Il transforme une vidéo en composant interactif où on ajoute des liens d'actions qui modifient la vidéo avec 8 ramifications : les liens interactifs, comme des boutons de jeux vidéo 3D avancés, apparaissent et permettent de modifier la scène. »", "1. **Vidéo → composant** : une vidéo source devient un composant web (lecteur + couche d'interaction) intégrable dans TabascoCity, Conspix ou un site client. 2. **Points d'action** : à des instants et des zones choisis, des boutons de jeu apparaissent (style HUD 3D, cf. esthétique HyperFrames / GSAP déjà en place). 3. **8 ramifications** : chaque bouton déclenche une variante de la scène générée à partir de la vidéo d'origine (changement d'action, de décor, de personnage), l'arbre est limité à 8 branches par nœud pour rester lisible et payable. 4. **Rendu** : les branches sont soit pré-générées (mode série, coût maîtrisé), soit générées à la demande (mode 2027, quasi temps réel).", "Générer une branche non modérée · dépasser 8 ramifications par nœud · publier sans validation."],
    features: ["**Vidéo → composant** : une vidéo source devient un composant web (lecteur + couche", "**Points d'action** : à des instants et des zones choisis, des boutons de jeu apparaissent", "**8 ramifications** : chaque bouton déclenche une variante de la scène générée à partir de", "**Rendu** : les branches sont soit pré-générées (mode série, coût maîtrisé), soit générées à"],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "MegaStudio · add-on",
    element: "studio",
    stats: {"autonomie": 4, "souverainete": 5, "integration": 4, "impact": 5, "installation": 5},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "operateur-de-nuit",
    name: "Opérateur de nuit",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/operateur-de-nuit.webp",
    pitch: "PME et mairies dont les logiciels métier n'ont pas d'API (gestion commerciale, paie, logiciels de collectivités, ERP anciens), cabinets, syndics.",
    description: ["le dirigeant fait la saisie le soir. Les intégrations n'existent pas, l'éditeur facture chaque connecteur, et les agents 2026 s'arrêtent à la première fenêtre modale.", "chaque nuit, il ouvre les logiciels comme un humain (computer use), rapproche les écritures, met à jour les stocks, prépare les documents du lendemain, réconcilie les fichiers entre outils, puis laisse un rapport et une liste d'exceptions à valider au matin. Il ne fait jamais d'action irréversible (envoi, paiement, suppression) sans validation.", "Gartner : 40 % des projets agentiques abandonnés d'ici fin 2027 pour coûts et valeur floue ; boucle infinie sur une popup ; licences logicielles interdisant l'automatisation ; coût tokens d'une nuit (à chiffrer avant de promettre, règle 08/09)."],
    features: [" Computer use de pointe : GPT-6 Astra « state of the art » en computer use, conçu pour travailler « directement dans le logiciel » (OpenAI, Axios) ; Claude Managed Agents (beta 8/04/2026) avec continuité de session et reprise d'erreur (InfoQ).", " METR : horizon 50 % à 16-20 h mais horizon 80 % seulement 3-4 h ; doublement tous les 3-4 mois (metr.org, Time Horizon 1.1).", " Le prérequis réel : un horizon 80 % supérieur à 8 h (une nuit) sur des interfaces graphiques, pas seulement sur du code. Si le doublement de 4 mois tient, c'est atteint entre mi-2027 et fin 2027. Anthropic reconnaît que « les sessions ne couvrent pas plusieurs jours nativement » en 2026 (inkeybit)."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "Toute structure à logiciels sans API",
    element: "temps",
    stats: {"autonomie": 5, "souverainete": 4, "integration": 5, "impact": 5, "installation": 3},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "pare-feu-anti-deepfake",
    name: "Pare-feu anti-deepfake",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/pare-feu-anti-deepfake.webp",
    pitch: "toute PME ayant un service trésorerie, cabinets comptables, trésoriers d'associations, régies municipales.",
    description: ["60 % des PME françaises ont subi au moins une tentative de fraude en 12 mois, 76 % des dirigeants estiment que l'IA augmente le risque (baromètre Allianz Trade 2026). 5 à 10 secondes d'audio suffisent à cloner une voix, pour moins de 50 EUR (cyberhack, yad). Alerte DGSI décembre 2025 sur une PME visée par le visage et la voix clonés de son dirigeant ; Banque de France alertée en avril 2026.", "il s'intercale sur les canaux de décision financière (téléphone SIP, visio, mail). Tout ordre de virement, changement de RIB ou demande urgente déclenche : (1) analyse deepfake audio/vidéo locale en temps réel, (2) rappel sur un canal de confiance, (3) vérification d'identité forte via le portefeuille européen (EUDI Wallet) ou France Identité, (4) double validation humaine tracée. Il tient un journal probatoire pour l'assureur.", "faux positifs qui bloquent un vrai paiement urgent ; biométrie = donnée sensible (AI Act Annexe III, échéance 2/12/2027) ; ne jamais stocker d'empreinte vocale sans base légale."],
    features: [" EUDI Wallet : mise à disposition par les États d'ici fin 2026 ; acceptation obligatoire pour banques, assureurs, télécoms, santé, énergie et entités AML à partir du 24/12/2027 (donneespersonnelles.fr, docaposte, Deloitte). C'est le levier qui rend la vérification forte généralisable à une PME.", " Détection deepfake audio/vidéo temps réel fiable en local (taux de faux positifs acceptable en production) : les modèles existent mais la course générateur/détecteur reste ouverte ; 2027 est une projection, pas une garantie.", " Visa Trusted Agent Protocol et Mastercard Agent Pay imposent déjà un Verified Agent ID et un consentement signé (eco.com) : le même schéma s'appliquera aux humains."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "PME · directions financières",
    element: "securite",
    stats: {"autonomie": 5, "souverainete": 4, "integration": 4, "impact": 5, "installation": 3},
    prix: null,
    prix_souverain: null,
  },
  {
    slug: "passeport-produit-vivant",
    name: "Passeport produit vivant",
    tag: "Agent · 2027 · avant-garde",
    date: "2027",
    img: "/monthly/passeport-produit-vivant.webp",
    pitch: "fabricants et importateurs de batteries industrielles > 2 kWh, VE et mobilité légère, puis (2027-2030) textile, électronique, mobilier, construction. Aucun seui",
    description: ["à partir du 18/02/2027, chaque batterie vendue dans l'UE doit avoir un passeport numérique accessible par QR (empreinte carbone, contenu recyclé, performance, durabilité) (arianee, passportcraft). Une PME n'a ni la donnée consolidée ni l'outil.", "il collecte la donnée chez les fournisseurs (fiches, ACV, certificats), calcule et versionne l'empreinte, génère le passeport et le QR, le publie sur le registre, met à jour à chaque changement de lot ou de fournisseur, et répond aux demandes des autorités et des clients. Il prépare aussi les futures catégories (textile, électronique).", "données fournisseurs manquantes ou fausses (l'agent signale, ne devine pas) ; responsabilité du fabricant, pas de l'agent ; format registre qui change."],
    features: [" Règlement ESPR (UE) 2024/1781 et règlement batteries : échéance ferme 18/02/2027.", " Registre européen DPP opérationnel et actes délégués par catégorie (calendrier 2026-2030) : formats définitifs encore en cours.", " Agents longue durée capables de tenir un dossier vivant sur des mois (Fable 5.1 1M contexte ; Managed Agents avec continuité de session) (InfoQ 8/04/2026)."],
    stack: ["Docker", "Traefik", "FastAPI", "Ollama / Qwen3"],
    price: "En vente en 2027 selon puissance du marché et Qbits",
    cta: "Être prévenu en 2027",
    future: true,
    edition: "Septembre 2026",
    type: "Industrie · PME produit",
    element: "conformite",
    stats: {"autonomie": 4, "souverainete": 4, "integration": 5, "impact": 4, "installation": 4},
    prix: null,
    prix_souverain: null,
  },
];
